### PR TITLE
Problem: does not handle dropped writer properly

### LINKED ISSUE #41: reader/writer issue
Not sure how this goes wrong, but...

open reader and writer
write small amount of data
attempt to read a large amount of data (blocks, too small)
close write handle

at this point, expected is that reader returns the data in buffer, and subsequent read returns 0.  instead, the reader gets dropped, the read request blocks, and the pipe doesn't terminate.

I'll post traces in a bit

### PR DESCRIPTION
**Pull request by hintjens**
When waiting for read, blocks if the writer drops. Solution is to
return a short read, or read_end if there's zero data.

Fixes #41.

### CODE REVIEW

**Comment by rpedde** [comment]
Travis doesn't like this.  Something about being bound to loopback on the travis vm?  Locally, the tests on this also fail on "read from pipe" in zpipes_test_cluster.c with a hang on my system.

**Comment by hintjens** [comment]
Travis raises a warning with Zyre, "ai_family not supported", but tests pass.

I've changed .travis.yml to use CZMQ 2.2.0 and ZeroMQ/4.0.4 since both these master trees are changing at the moment. I'm not getting any test failures on my various dev boxes. Can you try again?

**Comment by rpedde** [comment]
This totally worked against 2.2.0 and 4.0.4.

**Comment by hintjens** [comment]
OK, great!  Let's keep that as the baseline. I'm also testing against
libzmq and czmq master, but will avoid using any new features.

**Pull request merged**
